package: rcl_interfaces
messages:
  - name: Log
    path: msg
    stamp: stamp
    mapping:
      - {ros2.path: level, proton.signal: level, type: uint32}
      - {ros2.path: name, proton.signal: name, type: string}
      - {ros2.path: msg, proton.signal: msg, type: string}
      - {ros2.path: file, proton.signal: file, type: string}
      - {ros2.path: function, proton.signal: function, type: string}
      - {ros2.path: line, proton.signal: line, type: uint32}